MoonShard/urls.py
from django.contrib import admin
from django.urls import path, include
from xadmin.plugins import xversion
from underlord import views as ud_views
from django.conf import settings
from django.conf.urls.static import static

import xadmin
xadmin.autodiscover()
xversion.register_models()

urlpatterns = [
    path('', ud_views.index, name='index'),
    path('admin/', xadmin.site.urls),

    # path('', include('underlord.urls')),
    path('accounts/', include('underlord.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path(r'^notifications/', include('notifications.urls')),

    path('learning/', include('rubick.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rubick/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/12/17 15:36
# @Author  : Invoker
# @FileName: urls.py
# @Software: PyCharm

from django.urls import path, include
from . import views

app_name = 'rubick'
urlpatterns = [
    path('home/', views.ToHome().to_home, name='home'),
    path('newTopic/', views.new_topic, name='new_topic'),
    path('getTags/', views.get_tags, name='get_tags'),
    path('<str:topic_id>/detailTopic/', views.ToTopicDetail().get_topic_detail, name='get_topic_detail'),
    path('postTopic/', views.post_topic, name='post_topic'),
    path('doReply/', views.do_reply, name='do_reply'),
    path('doVote/', views.do_vote, name='do_vote'),
    path('doDeletePost', views.do_delete_post, name='do_delete_post'),
    path('doDeleteReply', views.do_delete_reply, name='do_delete_reply'),
]

rubick/forms.py
# -*- coding: utf-8 -*-
# @Time    : 2018/12/17 15:46
# @Author  : Invoker
# @FileName: forms.py
# @Software: PyCharm

from django.core.exceptions import ValidationError
from django import forms
from ckeditor.fields import RichTextFormField


class NewTopicForm(forms.Form):
    title = forms.CharField(label='标题',
                            max_length=100,
                            widget=forms.TextInput(attrs={'id': 'title',
                                                          'placeholder': '请输入主题标题',
                                                          'class': 'mdl-textfield__input'}),
                            error_messages={'required': '标题不能为空'})
    subject = RichTextFormField(label='内容',
                                max_length=4000,
                                widget=forms.Textarea(attrs={'id': 'subject',
                                                             'placeholder': '请在此输入内容'}),
                                required=False)

    def clean_title(self):
        title = self.cleaned_data.get('title')
        return title

    def clean_subject(self):
        subject = self.cleaned_data.get('subject')
        return subject



class PostForm(forms.Form):
    topic_id = forms.CharField(label='',
                               widget=forms.TextInput(attrs={'id': 'topic_id', 'type': 'hidden'}),
                               required=True)
    post = RichTextFormField(label='',
                             max_length=4000,
                             widget=forms.Textarea(attrs={'id': 'post', 'placeholder': '请在此输入内容'}),
                             required=True)

    def clean_post(self):
        post = self.cleaned_data.get('post')
        return post

    def clean_topic_id(self):
        topic_id = self.cleaned_data.get('topic_id')
        return topic_id


class ReplyForm(forms.Form):
    post_id = forms.CharField(label='',
                              widget=forms.TextInput(attrs={'id': 'post_id', 'type': ''}),
                              required=True)
    reply = RichTextFormField(label='',
                              max_length=4000,
                              widget=forms.Textarea(attrs={'id': 'reply', 'placeholder': '请在此输入内容'}),
                              required=True)

    def clean_reply(self):
        reply = self.cleaned_data.get('reply')
        return reply

    def clean_post_id(self):
        post_id = self.cleaned_data.get('post_id')
        return post_id

rubick/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import *
from underlord.models import News
from .forms import *
from underlord.views import check_login
from notifications.signals import notify

import datetime
import uuid

import logging

logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s - %(filename)s[line:%(lineno)d] - %(levelname)s: %(message)s')


# Create your views here.
class ToHome(ListView):

    def __init__(self):
        super(ToHome, self).__init__()
        self.model = Topic
        self.template_name = 'rubick/home.html'
        self.context_object_name = 'all_topics'
        self.home_topics = []
        self.data = {}

    def to_home(self, request):
        self.home_topics = []
        self.data.clear()
        if request.method == 'GET' or request.method == 'POST':
            try:
                topics = Topic.objects.all()
                for i in range(0, len(topics)):
                    posts = Post.objects.filter(topic=topics[i]).all()
                    score_t = 2*len(Topic.objects.filter(starter=topics[i].starter).all())
                    score_p = len(Post.objects.filter(created_by=topics[i].starter).all())
                    score = score_t + score_p
                    topic_detail = {'topic_id': topics[i].topic_id,
                                    'title': topics[i].title,
                                    'subject': str(topics[i].subject[:50]) + '...',
                                    'like': topics[i].like,
                                    'posts': len(posts),
                                    'views': topics[i].views,
                                    'created_at': topics[i].created_at,
                                    'updated_at': topics[i].updated_at,
                                    'starter': topics[i].starter,
                                    'score': score}
                    topic_tag = TopicTag.objects.filter(topic__title=topic_detail['title']).all()
                    tags = []
                    for j in range(0, len(topic_tag)):
                        tag = topic_tag[j].tag
                        tag_info = {
                            'tag': tag.title,
                            'color': tag.color,
                            'color_hover': tag.color_hover
                        }
                        tags.append(tag_info)
                        topic_detail['tags'] = tags
                    self.home_topics.append(topic_detail)
                # add pages
                paginator = Paginator(self.home_topics, 5)
                page = request.GET.get('page')
                try:
                    all_topics = paginator.page(page)
                except PageNotAnInteger:
                    all_topics = paginator.page(1)
                except EmptyPage:
                    all_topics = paginator.page(paginator.num_pages)

                news = News.objects.all()[:6]
                return render(request, self.template_name, {'all_topics': all_topics,
                                                            'topic_amount': len(topics),
                                                            'news_6':news,
                                                            'data': self.data})
            except:
                self.data['ERROR_CODE'] = 'CNF500'  # can not found object
                return render(request, '500.html', {self.context_object_name: self.home_topics, 'data': self.data})
        else:
            self.data['ERROR_CODE'] = 'MNA403'  # method not allowed
            return render(request, '500.html', {'data': self.data})


@check_login
def new_topic(request):
    data = {}
    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            try:
                title = form.cleaned_data['title']
                subject = form.cleaned_data['subject']
                topic_id = str(uuid.uuid3(uuid.NAMESPACE_DNS, title)).replace('-', '')
                tags = ['']
                Topic.objects.create(topic_id=topic_id,
                                     title=title,
                                     subject=subject,
                                     starter=request.user,
                                     tags=tags,
                                     board='rubick').save()
                data['message'] = 'CS200'  # create succeed
                return ToHome().to_home(request)
            except:
                data['ERROR_CODE'] = 'CNF500'  # can not found object
                return render(request, '500.html', {'data': data})
        else:
            data['ERROR_CODE'] = 'FNV500'  # form not valid
            return render(request, '500.html', {'data': data})
    else:
        tags = Tag.objects.all()
        form = NewTopicForm()
        return render(request, 'rubick/new_topic.html', {'form': form, 'tags': tags})


@check_login
def post_topic(request):
    data = {}
    # redirect_to = request.POST.get('next', request.GET.get('next', ''))
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            try:
                message = form.cleaned_data['post']
                post_id = str(uuid.uuid4()).replace('-', '')
                topic_id = form.cleaned_data['topic_id']
                topic = Topic.objects.filter(topic_id=topic_id).all()[0]
                username = request.user.username
                created_by = User.objects.filter(username=username).all()[0]
                updated_by = User.objects.filter(username=username).all()[0]
                logging.info(topic_id)
                Post.objects.create(post_id=post_id,
                                    message=message,
                                    topic=topic,
                                    created_by=created_by,
                                    updated_by=updated_by).save()
                notify.send(created_by, recipient=topic.starter, verb=topic.topic_id, level='post')
                return redirect(topic)
            except:
                data['ERROR_CODE'] = 'CNC500'  # can not create object
                return render(request, '500.html', {'data': data})
        else:
            data['VALID_MSG'] = form.errors
            data['ERROR_CODE'] = 'FNV500'  # form not valid
            return render(request, '500.html', {'data': data})
    else:
        form = PostForm()

    return render(request, 'rubick/detail_topic.html', {'form': form})


@csrf_exempt
def do_reply(request):
    if request.method == 'POST':
        try:
            reply_id = str(uuid.uuid4()).replace('-', '')
            post_id = request.POST.get('post_id')
            post = Post.objects.get(post_id=post_id)
            message = request.POST.get('reply')
            user = request.user
            Reply.objects.create(reply_id=reply_id,
                                 message=message,
                                 post=post,
                                 created_by=user,
                                 updated_by=user).save()
            return JsonResponse(200, safe=False)
        except:
            return JsonResponse(500, safe=False)
    else:
        return JsonResponse(400, safe=False)


@csrf_exempt
def get_tags(request):
    if request.method == 'POST':
        title = request.POST.get('tag')
        try:
            tag = Tag.objects.filter(title=title).all()[0]
            return JsonResponse(tag.title, safe=False)
        except:
            return JsonResponse(500, safe=False)
    else:
        return JsonResponse(500, safe=False)


class ToTopicDetail(ListView):

    def __init__(self):
        super(ToTopicDetail, self).__init__()
        self.model = Post
        self.template_name = 'rubick/detail_topic.html'
        self.context_object_name = ''
        self.home_topics = []
        self.data = {}

    def get_topic_detail(self, request, topic_id):
        all_posts_db_change = []
        all_replys = []
        all_post_score = []
        data = {}
        if request.method == 'GET':
            try:
                # topic_id = request.GET.get('topic_id')
                topic = Topic.objects.filter(topic_id=topic_id).all()[0]
                views = topic.views + 1
                _topic = Topic.objects.get(topic_id=topic_id)
                _topic.views = views
                _topic.save()
                all_tags = TopicTag.objects.filter(topic=topic).all()
                all_posts_db = Post.objects.filter(topic=topic).all()
                _topics = Topic.objects.filter(starter=topic.starter).all()
                _posts = Post.objects.filter(created_by=topic.starter).all()
                topic_starter_score = 2*len(_topics) + len(_posts)
                for post in all_posts_db:
                    _p_topics = Topic.objects.filter(starter=post.created_by).all()
                    _p_posts = Post.objects.filter(created_by=post.created_by).all()
                    post_starter_score = 2 * len(_p_topics) + len(_p_posts)
                    p_score = {post.created_by: post_starter_score}
                    if p_score not in all_post_score:
                        all_post_score.append(p_score)
                    all_posts_db_change.append(post)
                    post_replys = Reply.objects.filter(post=post).all()
                    all_replys.append(post_replys)

                logging.info(all_post_score)
                form = PostForm(initial={'topic_id': topic_id})
                paginator = Paginator(all_posts_db_change, 5)
                page = request.GET.get('page')
                try:
                    all_posts = paginator.page(page)

templates/rubick/home.html
{% extends 'base_board.html' %}

{% block title %}开始学习{% endblock %}

{% block board_title %}开始学习{% endblock %}

{% block new_topic_url %}{% url 'rubick:new_topic' %}{% endblock %}

{% block topic_num %}1140{% endblock %}

{% block topic-summary %}
    {% for topic in all_topics.object_list  %}
        <div class="topic-summary">
            <div class="stats-container">
                <div class="like-stats">
                    <div class="likes-stats-circle">
                        <span class="likes"><strong>{{ topic.like }}</strong></span>
                        <div class="viewcount">喜欢</div>
                    </div>
                </div>
                <div class="answered-stats">
                    <div class="answered-stats-circle">
                        <span class="answers"><strong>0</strong></span>
                        <div class="viewcount">回答</div>
                    </div>
                </div>
                <div class="view-stats">
                    <div class="view-stats-circle">
                        <span class="views"><strong>{{ topic.views }}</strong></span>浏览
                    </div>
                </div>
            </div>
            <div class="summary">
                <div class="summary-title">
                    <h5 class="summary-title-content">
                        <a href="{% url 'rubick:get_topic_detail' %}?topic_id={{ topic.topic_id }}">{{ topic.title }}</a>
                    </h5>
                </div>
                <div class="excerpt">
                    <p>{{ topic.subject }}</p>
                </div>
                <div class="summary-info">
                    <div class="tags">
                        {% for tag in topic.tags %}
                            <div class="tags-content">
                                <div class="tag" style="background-color: {{ tag.color }}">
                                    <div class="tag-bg">
                                        <a href="#">{{ tag.tag }}</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="author-info">
                        <div class="author-content">
                            <div class="author-avatar">
                                <img class="avatar-img" src="http://120.79.209.94:9000/static/background.png">
                            </div>
                            <div class="author-msg">
                                <div class="author-name"><a href="#">{{ topic.starter }}</a></div>
                                <div class="author-answers">1024</div>
                            </div>
                        </div>
                        <div class="created-time">{{ topic.created_at }}</div>
                    </div>
                </div>
            </div>
        </div>
        {{ all_topics.full_name | upper }}
    {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if all_topics.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ all_topics.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ all_topics.number }} of {{ all_topics.paginator.num_pages }}.
            </span>

            {% if all_topics.has_next %}
                <a href="?page={{ all_topics.next_page_number }}">next</a>
                <a href="?page={{ all_topics.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

templates/rubick/new_topic.html
{% extends 'base.html' %}

{% block title %}新建学习主题{% endblock %}
{% block media_link %}{{ form.media }}{% endblock %}
{% block content %}
    <div class="flex-center" style="margin: auto">
        <div class="container">
            <div class="flex-center" >
                <div class="new_topic_content">
                    <div class="new_topic_title">
                        <h3>新建·学习主题</h3>
                    </div>
                    <form class="form" action="{% url 'rubick:new_topic' %}" method="post">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="new_topic_form">
{#                            标题#}
                            <span class="mdl-chip mdl-chip--contact">
                                <span class="mdl-chip__contact mdl-color--teal mdl-color-text--white">A</span>
                                <span class="mdl-chip__text">{{ form.title.label_tag }}</span>
                            </span>
                            <div class="mdl-textfield mdl-js-textfield" style="width: 100%">
                                {{ form.title }}
                                <label class="mdl-textfield__label" for="sample1">Text...</label>
                            </div>
                            <br>

{#                            主题#}
                            <span class="mdl-chip mdl-chip--contact">
                                <span class="mdl-chip__contact mdl-color--teal mdl-color-text--white">B</span>
                                <span class="mdl-chip__text">{{ form.subject.label_tag }}</span>
                            </span>
                            <br>
                            {{ form.subject }}
                            <br>

{#                            标签#}
{#                            <span class="mdl-chip mdl-chip--contact">#}
{#                                <span class="mdl-chip__contact mdl-color--teal mdl-color-text--white">C</span>#}
{#                                <span class="mdl-chip__text">{{ form.tags.label_tag }}</span>#}
{#                            </span>#}
{#                             <div class="mdl-textfield mdl-js-textfield">#}
{#                                {{ form.tags }}#}
{#                                <label class="mdl-textfield__label" for="sample1">Text...</label>#}
{#                            </div>#}

                        </div>
                        <button type="submit" id="demo-show-toast" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" style="background-color: #009688 !important">新建</button>
                        <div id="demo-toast-example" class="mdl-js-snackbar mdl-snackbar">
                          <div class="mdl-snackbar__text"></div>
                          <button class="mdl-snackbar__action" type="button"></button>
                        </div>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                    <br>
                    <div class="blank-bk" style="height: 200px"></div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block script_content %}
    <script>
        function get_tags() {
            var input_tag = $("#tags").val();
            $.ajax({
                type: 'POST',
                url: '{% url "rubick:get_tags" %}',
                data: {
                    'tag': input_tag,
                },
                success: function (data) {
                    console.info(data);
                    $("#related-tags").css("visibility", "visible");
                    $("#related-tags").html("<span>" + data + "</span>");
                }
            });
        }

        (function() {
            'use strict';
            var snackbarContainer = document.querySelector('#demo-toast-example');
            var showToastButton = document.querySelector('#demo-show-toast');
            showToastButton.addEventListener('click', function() {
                'use strict';
                var data = {message: '主题新建成功！ '};
                snackbarContainer.MaterialSnackbar.showSnackbar(data);
            });
        }());

    </script>


{% endblock %}