MoonShard/urls.py
from django.contrib import admin
from django.urls import path, include
from xadmin.plugins import xversion
from underlord import views as ud_views
from django.conf import settings
from django.conf.urls.static import static

import xadmin
xadmin.autodiscover()
xversion.register_models()

urlpatterns = [
    path('', ud_views.index, name='index'),
    path('admin/', xadmin.site.urls),

    # path('', include('underlord.urls')),
    path('accounts/', include('underlord.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path(r'^notifications/', include('notifications.urls')),

    path('learning/', include('rubick.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rubick/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/12/17 15:36
# @Author  : Invoker
# @FileName: urls.py
# @Software: PyCharm

from django.urls import path, include
from . import views

app_name = 'rubick'
urlpatterns = [
    path('home/', views.ToHome().to_home, name='home'),
    path('newTopic/', views.new_topic, name='new_topic'),
    path('getTags/', views.get_tags, name='get_tags'),
    path('<str:topic_id>/detailTopic/', views.ToTopicDetail().get_topic_detail, name='get_topic_detail'),
    path('postTopic/', views.post_topic, name='post_topic'),
    path('doReply/', views.do_reply, name='do_reply'),
    path('doVote/', views.do_vote, name='do_vote'),
    path('doDeletePost', views.do_delete_post, name='do_delete_post'),
    path('doDeleteReply', views.do_delete_reply, name='do_delete_reply'),
]

underlord/urls.py
from django.urls import path, include
from . import views

app_name = 'underlord'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('userInfo/<str:username>/', views.to_user_info, name='userInfo'),
    path('doFollow/', views.do_follow, name='do_follow'),
    path('doCancelFollow/', views.do_cancel_follow, name='do_cancel_follow'),
    path('updateUser/', views.update_user, name='update_user'),
    path('userTopicsSelf/', views.ToUserAllTopics().all_users_topic_self, name='user_topics_self'),
    path('userTopicsOther/', views.ToUserAllTopics().all_users_topic_other, name='user_topics_other'),
    path('userFollows/', views.ToMyFollows().to_my_follows, name='to_my_follows'),
    path('toMsgBox/', views.to_msg_box, name='to_msg_box'),
    path('doMsgSend/', views.do_msg_send, name='do_msg_send'),
    path('doMarkRead/', views.do_mark_read, name='do_mark_read'),
    path('toAllUsers/', views.ToAllUsers().to_all_users, name='to_all_users'),
    path('ToAllTags/', views.ToAllTags().to_all_tags, name='to_all_tags'),
    path('ToTagTopics/', views.ToTagTopics().to_tag_topics, name='to_tag_topics'),


    path('doDeleteTopic', views.do_delete_topic, name='do_delete_topic'),
]

xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/_pagination.html
{% load i18n %}
<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="?{{ page_obj.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; {% trans "previous" %}</a>
    {% else %}
        <span class="disabled prev">&lsaquo;&lsaquo; {% trans "previous" %}</span>
    {% endif %}
    {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <span class="current page">{{ page }}</span>
            {% else %}
                <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a href="?{{ page_obj.next_page_number.querystring }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a>
    {% else %}
        <span class="disabled next">{% trans "next" %} &rsaquo;&rsaquo;</span>
    {% endif %}
</div>

templates/base.html
{% load staticfiles %}
{% load notifications_tags %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <link rel="stylesheet" href="https://unpkg.com/nprogress@0.2.0/nprogress.css">
{#    <link rel="stylesheet" href="{% static 'css/nprogress.css' %}">#}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <link rel="stylesheet" href="{% static 'css/base-board.css' %}">
    <link rel="stylesheet" href="{% static 'css/base-topic.css' %}">
    {% block media_link %} {% endblock %}
    <title>{% block title %}title{% endblock %}</title>
</head>
<body>
    <div class="mdl-layout mdl-js-layout">
        <header class="mdl-layout__header mdl-layout__header--scroll" id="header">
        <!-- Top row, always visible -->
        <div class="mdl-layout__header-row" id="layout-head">
            <!-- Title -->
            <span class="mdl-layout-title"><a href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}"> </a></span>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right"
                 style="margin-left: 20px; " id="search-input-div">
                <input class="mdl-textfield__input" type="text" name="sample"
                id="waterfall-exp" placeholder="你想要找什么？">
                <i class="icon-search"></i>

            </div>


            <!-- Navigation -->
            <nav class="mdl-navigation" id="head-navigation">
                <a class="mdl-navigation__link" href="{% url 'rubick:home' %}">学习</a>
                <a class="mdl-navigation__link" href="">生活</a>
                <a class="mdl-navigation__link" href="">感情</a>
                <a class="mdl-navigation__link" href="">市场</a>
            </nav>
            <div class="mdl-layout-spacer"></div>


            {% if user.is_authenticated %}
                <div id="head-msg">
                    <span class="mdl-badge" data-badge="{% notifications_unread  %}" id="btn0">
                        <button class="mdl-button mdl-js-button mdl-js-ripple-effect" id="btn0" style="color: grey">
                            我的动态
                        </button>
                        <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right" for="btn0">
                            <li class="mdl-menu__item">
                                <a href="{% url 'underlord:user_topics_self' %}">主题动态</a>
                                <span style="color: red;display: none" id="post-point">•</span>
                            </li>
                            <li class="mdl-menu__item">
                                <a href="{% url 'underlord:to_my_follows' %}">好友消息</a>
                                <span style="color: red;display: none" id="info-point">•</span>
                            </li>
                        </ul>
                    </span>
                </div>

                <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="btn1">
                    {% block self_avatar %}
                        <img src="{{ request.user.avatar.url }}" style="height: 40px; width: 40px;">
                    {% endblock %}
                </button>
                <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right" for="btn1">
                    <li class="mdl-menu__item" disabled>以<b>{{ request.user.username }}</b>登录</li>
{#                        <li class="mdl-menu__item" disabled></li>#}
                    <hr/>
                    <li class="mdl-menu__item"><a href="{% url 'underlord:userInfo' request.user.username %}">个人中心</a></li>
                    <li class="mdl-menu__item"><a href="{% url 'underlord:user_topics_self' %}">我的主题</a></li>
                    <li class="mdl-menu__item"><a href="{% url 'underlord:to_my_follows' %}">我的关注</a></li>
                    <li class="mdl-menu__item"><a href="{% url 'logout' %}">注销登录</a></li>
                </ul>
            {% else %}
                <span class="head-register-login">
                    <a href="{% url "login" %}?next={{ request.path }}">登录</a>
                    <a href="{% url "underlord:register" %}?next={{ request.path }}">注册</a>
                </span>
            {% endif %}

        </div>
    </header>
        <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">MoonShard</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="{% url 'rubick:home' %}">学习</a>
            <a class="mdl-navigation__link" href="">生活</a>
            <a class="mdl-navigation__link" href="">感情</a>
            <a class="mdl-navigation__link" href="">市场</a>
        </nav>
    </div>

        <main class="mdl-layout__content">
            <div class="page-content"><!-- Your content goes here -->
                {% block content %}{% endblock %}
            <div class="news">
                <div class="news-circle">
                    {% block news %}{% endblock %}
                </div>
            </div>
            </div>
            <footer class="mdl-mega-footer" id="footer" >
        <div class="mdl-mega-footer__middle-section">

            <div class="mdl-mega-footer__drop-down-section">
                <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
                <h1 class="mdl-mega-footer__heading">社区特点</h1>
                <ul class="mdl-mega-footer__link-list">
                    <li><a href="#">关于</a></li>
                    <li><a href="#">条款</a></li>
                    <li><a href="#">伙伴</a></li>
                    <li><a href="#">更新</a></li>
                </ul>
            </div>

            <div class="mdl-mega-footer__drop-down-section">
                <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
                <h1 class="mdl-mega-footer__heading">产品</h1>
                <ul class="mdl-mega-footer__link-list">
                    <li><a href="#">团队</a></li>
                    <li><a href="#">工具</a></li>
                    <li><a href="#">资源</a></li>
                </ul>
            </div>

            <div class="mdl-mega-footer__drop-down-section">
                <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
                <h1 class="mdl-mega-footer__heading">技术</h1>
                <ul class="mdl-mega-footer__link-list">
                    <li><a href="#">如何实现</a></li>
                    <li><a href="#">模式</a></li>
                    <li><a href="#">使用</a></li>
                    <li><a href="#">产品</a></li>
                    <li><a href="#">条款</a></li>
                </ul>
            </div>

            <div class="mdl-mega-footer__drop-down-section">
                <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
                <h1 class="mdl-mega-footer__heading">FAQ</h1>
                <ul class="mdl-mega-footer__link-list">
                    <li><a href="#">问题</a></li>
                    <li><a href="#">回答</a></li>
                    <li><a href="#">联系我们</a></li>
                </ul>
            </div>

        </div>

        <div class="mdl-mega-footer__bottom-section">
            <div class="mdl-logo">Moon Shard</div>
            <ul class="mdl-mega-footer__link-list">
                <li><a href="#">帮助</a></li>
                <li><a href="#">隐私权和条款</a></li>
            </ul>
        </div>

    </footer>
        </main>
    </div>
    <script
        src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script src="https://unpkg.com/nprogress@0.2.0/nprogress.js"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js"></script>

    <script src="{% static 'js/main.js' %}"></script>
    <script>
        window.onload = function () {
            {% for noti in request.user.notifications.unread %}
                {% if noti.level == 'info' %}
                    $('#info-point').show();
                {% elif noti.level == 'post' %}
                    $('#post-point').show();
                {% endif %}
            {% endfor %}
        };
    </script>
    {% block script_content %}{% endblock %}
</body>
</html>

templates/base_board.html
{% extends 'base.html' %}

{% block title %} base_board {% endblock %}

{% block content %}
    <div class="page-content-main">
        <div class="left-sidebar">
            <div class="left-sidebar-content">
                <ol style="line-height: 30px">
                    <li>
                        <a href="{% url 'index' %}" class="li-index" style="padding-left: 5%">
                            <span>首页</span>
                        </a>
                    </li>
                    <li style="background-color: #f3f3f3;border-right: 3px solid #0366d6;height: 30px;">
                        <a href="{% url 'rubick:home' %}" class="li-index" style="padding-left: 10%">
                            <span><strong>Moon Shard</strong></span>
                        </a>
                    </li>
                    <ol>
                        <li>
                            <a href="{% url 'underlord:to_all_tags' %}" class="li-tag">标签</a>
                        </li>
                        <li>
                            <a href="{% url 'underlord:to_all_users' %}" class="li-user">用户</a>
                        </li>

                    </ol>
                </ol>
            </div>
        </div>
        <div class="contents">
            <div class="contents-head">
                <div class="contents-head-circle">
                    <div class="head-title">
                        <h5><strong>{% block board_title %}board_title{% endblock %}</strong></h5>
                        <button id="btn_new_topic" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect"
                        onclick="window.location.href='{% block new_topic_url %}new_topic_url{% endblock %}'">
                            新建主题
                        </button>
                    </div>
                    <div>
                        <p>超过<span class="span_topic_num">{% block topic_num %}topic_num{% endblock %}</span>个主题</p>
                    </div>
                </div>

            </div>

            <div class="contents-content">
                {% block topic-summary %}

                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base_topic.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <div class="page-content-main">
        <div class="left-sidebar">
            <div class="left-sidebar-content">
                <ol style="line-height: 30px">
                    <li>
                        <a href="{% url 'index' %}" class="li-index" style="padding-left: 5%">
                            <span>首页</span>
                        </a>
                    </li>
                    <li style="background-color: #f3f3f3;border-right: 3px solid #0366d6;height: 30px;">
                        <a href="{% url 'rubick:home' %}" class="li-index" style="padding-left: 10%">
                            <span><strong>Moon Shard</strong></span>
                        </a>
                    </li>
                    <ol>
                        <li>
                            <a href="{% url 'underlord:to_all_tags' %}" class="li-tag">标签</a>
                        </li>
                        <li>
                            <a href="{% url 'underlord:to_all_users' %}" class="li-user">用户</a>
                        </li>

                    </ol>
                </ol>
                </ol>
            </div>
        </div>


        <div class="topic-contents">
            <div class="topic-contents-head">
                <div class="topic-contents-head-circle">
                    <div class="topic-head-title">
                        <h5 class="topic-title-h5"><strong>{% block topic_title %}topic_title{% endblock %}</strong></h5>
                        <button id="btn_new_topic" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect"
                        onclick="window.location.href='{% block new_topic_url %}new_topic_url{% endblock %}'">
                            新建主题
                        </button>
                    </div>
                </div>

            </div>

            <div class="topic-detail">
                <div class="topic-mainbar">
{#                    主题主体#}
                    <div class="topic-host">
                        <div class="topic-host-1">
                            <div class="js-voting-container-circle">
                                <div class="js-voting-container">
                                    <button id="topic-js-vote-up-btn" class="js-vote-up-btn mdl-button mdl-js-button">△</button>
                                    <div id="js-vote-count" class="js-vote-count">{% block topic_vote_count %}0{% endblock %}</div>
                                    <button id="topic-js-vote-down-btn" class="js-vote-down-btn mdl-button mdl-js-button">▽</button>
                                </div>
                            </div>
                            <div class="topic-subject">
                                {% block topic_subject %}{% endblock %}
                            </div>
                        </div>
                        <div class="topic-host-2">
                            <div class="author-info">
                                {% block topic_author %}{% endblock %}
                            </div>
                        </div>
                    </div>

{#                    主题所有回复#}
                    <div class="topic-reply">
                        {% block topic_reply %}{% endblock %}
                    </div>
                    <div class="topic-pagination">
                        {% block topic_pagination %}{% endblock %}
                    </div>
                    <div class="post-box">
                        {% block post_box %}{% endblock %}
                    </div>
                </div>
                <div class="topic-right-sidebar">
                    <div class="topic-info">
                        {% block topic_info %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}